### ISSUE TITLE
dess command

### ISSUE THREAD

**Issue by valanths1990** [Elfocrash/L2Autobots#2]
dess command is also broken
here is the fix:

                       val bots = ViewStates.indexViewState(activeChar).selectedBots.filter { it.value.isOnline }

                        CoScopes.generalScope.launch {
                            bots.forEach {
                                innerLaunch@CoScopes.massDespawnerScope.launch {
                                    val autobot = AutobotsManager.activeBots.getOrDefault(it.value.name, null) ?: return@innerLaunch
                                    AdminActions.despawnAutobot(autobot)
                                }
                            }
                        }
                        ViewStates.indexViewState(activeChar).selectedBots.clear()`

**Comment by Elfocrash** [comment]
Committed thanks!
